sudo: required
language: go
go:
  - "1.10.x"
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce libtool pkg-config build-essential autoconf automake uuid-dev wget
  - sudo docker run -p 5555:5555 -p 5556:5556 -d --name zest --rm jptmoore/zest:v0.0.7 /app/zest/server.exe --secret-key-file example-server-key --enable-logging
  - sudo docker run -p 4444:4444 -p 4445:4445 -d --name arbiter --rm jptmoore/arbiter /app/zest/server.exe --request-endpoint tcp://0.0.0.0:4444 --secret-key-file example-server-key --token-key-file example-token-key --enable-logging
  - wget https://github.com/zeromq/libzmq/releases/download/v4.2.3/zeromq-4.2.3.tar.gz
  - tar xvzf zeromq-4.2.3.tar.gz
  - cd zeromq-4.2.3; ./configure; sudo make install; sudo ldconfig; cd ..; sudo rm -rf zeromq-4.2.3
  - if [ -d "$HOME/gopath/src/github.com/Toshbrown" ]; then mv $HOME/gopath/src/github.com/Toshbrown $HOME/gopath/src/github.com/toshbrown; fi
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - docker